### ISSUE TITLE
training parameters url is 404: not found

### ISSUE THREAD

**Issue by Osborn28** [mbrossar/ai-imu-dr#1]
hi, training parameters url is not found, please check it (https://cloud.mines-paristech.fr/index.php/s/5wjlZpZPEgV8l9p/download). And I am sorry that I have not had time to read the paper carefully. I would like to ask if this method is suitable for general scenes or for the more stringent requirements of model parameters. Thank you.

**Comment by mbrossar** [comment]
I have fixed cloud trouble.

Can you describe what you think about "general scenes or for the more stringent requirements of model parameters" ?
