### ISSUE TITLE
Lie groups

### ISSUE THREAD

**Issue by prayritkhanna** [mbrossar/ai-imu-dr#10]
Hello, 

I keep getting an error that says modulenotfounderror: liegroups. I was wondering what this is. 

I found on the internet that this is apart of the utils package however it is not referenced anywhere in your code. 

Could you please explain where this is coming from?

**Comment by eugenelyj** [comment]
i also met this problem. How did solve it? : )

**Comment by mbrossar** [comment]
You can install the liegroups package https://github.com/utiasSTARS/liegroups
