### ISSUE TITLE
Loss_train

### ISSUE THREAD

**Issue by prayritkhanna** [mbrossar/ai-imu-dr#11]
Hello,

I was wondering what the loss_train variable does inside of train_torch_filter. I would also like to know where the checkpoint is in your code. If I needed to stop running the code for some reason, I just wanted to make sure that there is a checkpoint saving where I have stopped. 

Thanks

**Comment by mbrossar** [comment]
loss_train is the loss function error between ground truth and estimates.
Since the dataset is relatively small, no checkpoint is used. You can add it by yourself.
