### ISSUE TITLE
 path_data_base = "./media/mines/46230797-4d43-4860-9b76-ce35e699ea47/KITTI/raw"

### ISSUE THREAD

**Issue by gaomomo** [mbrossar/ai-imu-dr#14]
Hi,
path_data_base = "./media/mines/46230797-4d43-4860-9b76-ce35e699ea47/KITTI/raw",
I want to know if this path needs to be manually created locally. What data is placed under this path?

Thank you so much in advance.

**Comment by prayritkhanna** [comment]
I have a similar question, when I set the read_data = 1, I get back an error saying there is no such directory: "./media/mines/46230797-4d43-4860-9b76-ce35e699ea47/KITTI/raw". Is there something that I need to do to make read_data work?
![Screenshot from 2019-06-11 10-57-31](https://user-images.githubusercontent.com/33380945/59295144-d23fd780-8c37-11e9-82d2-0c76d0b1779b.png)

**Comment by mbrossar** [comment]
You have to modify this path depending on where you store the KITTI data.

**Comment by gaomomo** [comment]
Thank you so much for answering my question.
I want to know what data is placed respectively under these two paths：
./media/mines/46230797-4d43-4860-9b76-ce35e699ea47/KITTI/raw  and   ../data

**Comment by prayritkhanna** [comment]
@gaomomo

The first path is the Kitti raw data. This is the data you will be testing/training.

 The "../data" path is where the data should be saved on your system within the ai-imu-dr directory. 
You need to create that directory if you do have one already in there.

**Comment by gaomomo** [comment]
Thanks a lot!

**Comment by Akudavale** [comment]
> You have to modify this path depending on where you store the KITTI data.
from where do i get this KITTI data? 
Thankyou
