### ISSUE TITLE
evaluate translation error and rotation error on KITTI benchmark

### ISSUE THREAD

**Issue by LongruiDong** [mbrossar/ai-imu-dr#15]
Hi,
Thanks for sharing this great work!
I read your paper and found the results in Table 1,which shows Translation Error and Rotational Error. But the data in your project code is 100 Hz so we got estimated poses with 100 Hz, while Kitti Visual Odometry benchmark(11 training sequences) is 10 Hz, they are not correctly synchronized although just downsample the raw data(100 Hz) to 10Hz. Therefore I don not know how to compute correctly translation error / rotation error with[ Odometry development kit](https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_odometry.zip) from http://www.cvlibs.net/datasets/kitti/eval_odometry.php.
Can you explain in detail how the results in the Table 1 are calculated?
Thank you so much for reply~

**Comment by mbrossar** [comment]
Hi,
On raw data, you have ground truth at 100hz. I take this ground truth and the estimates, subsample them at 10 Hz and compute error as in the odometry development kit.

I also presume that even if you synchronize estimates with the closest timestamp of the 10 Hz ground truth, it will give similar result (0.01s synchronization error for trajectory of more than 100 m is négligeable)
