### ISSUE TITLE
I can not  download the odometry development kit 

### ISSUE THREAD

**Issue by gaomomo** [mbrossar/ai-imu-dr#18]
Hello,
you have computed the tranlation error and rotation error with odometry development kit, but I can not download it. Could you please provide me with an alternative link that I can use to download the development kit? Thank you very much!

**Comment by mbrossar** [comment]
You can download the development kit on the Kitti dataset. `[https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_odometry.zip](https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_odometry.zip)`
