### ISSUE TITLE
Fusing GPS measurements

### ISSUE THREAD

**Issue by amakurin** [mbrossar/ai-imu-dr#26]
Hello, Martin!
If i want to fuse GPS measurements of position\velocity (which are left invariant in nature) with this RIEKF estimated state should i just do LIEKF propagation\update considering RIEKF state as "previous step" (N-1) state? or there is some special method to do this? Thank you very much for help!
UPD: or maybe it is pretty correct to just use method you showed in #22 with Y(X)=p

**Comment by amakurin** [comment]
I've used method from #22 ignoring "left invariance" aspect of GPS observations, and got acceptable results.

**Comment by mbrossar** [comment]
Hi, 

Sorry for delay. 

I would said something similar as you can add GPS measurements in the right error that loss theoretical left property of left error. But I think it is clearly more simple. 

Martin

Le 26 août 2019 à 09:35, à 09:35, Alexey Makurin <notifications@github.com> a écrit:
