### ISSUE TITLE
Huge Position uncertainty

### ISSUE THREAD

**Issue by amakurin** [mbrossar/ai-imu-dr#28]
Hello again!
Using RIEKF framework (on SE2(3) group as in preliminary paper from RINS-W) i've noticed that with ZUPT, LAT, UP pseudo measurements uncertainty of position reaches huge numbers with order of 1e+5(6..7..). Which can be explained by the fact that we never measure position, but only predict it. But... with time (~20sec with 100hz) this huge numbers give negative influence on filter's stability. Did you experience this issue in your experiments? or maybe it just caused by my mistakes in filter architecture... Thank you very much for help!

**Comment by mbrossar** [comment]
Hi, 

I believe you do not talk about the measurement covariance but about the covariance of the position of the state estimate. 

It is logical to have high values. If you have 10^6 value it's just say one kilometer variance. I have same values but for more than 20 s (frequency does not play a role) . 

Combined with covariance for bias, 10^-9, it can clearly lead to numerical problem. 

I know three solutions. The more simple is to have number in double format, it is what I did in this repo and is sufficient. You can also change the unit in the covariance from meter to km you win a factor 6. The best but more complex in to implement the filter in square root form. Just search square root kalman filter on google. 

Best

Martin

Le 26 août 2019 à 09:47, à 09:47, Alexey Makurin <notifications@github.com> a écrit:

**Comment by amakurin** [comment]
Got your point. Thanks!

**Comment by EdernOllivier** [comment]
You need to better initialisé your position and Also that the covariances of measurements should be known.

**Comment by EdernOllivier** [comment]
Sorry initialise
