### ISSUE TITLE
unable to process with kitti dataset

### ISSUE THREAD

**Issue by rickeshtn** [mbrossar/ai-imu-dr#33]
Dear Martin Brossar, first of all thank you for such a great paper and making the code public. I have spent couple weeks on getting it run with the kitti dataset. But i am not able to do so. In one of the issues you had solved the same. But it is to vain, I get the below error irrespective of which kitti dataset i try.  i have pointed the directory to the top level of kitti dataset, the path looks like 

> /dataset/kitti/2011_09_26/2011_09_26_drive_0019_sync 

But still it throws the below error. 

![image](https://user-images.githubusercontent.com/28569449/66016705-529d8780-e50a-11e9-86d3-e4814117b728.png)

**Comment by sharish33** [comment]
Hi,

I am facing the same issue while implementing with kitti dataset(2011_09_30_drive_0034) and setting readdata=1
the variable I set as below:
path_data_base = "/home/gsp_hs/Downloads/2011_09_30/2011_09_30_drive_0034_sync"

Please can you let know how you resolved the issue.

Best Regards,
Hareesh
