### ISSUE TITLE
The initialization of b_acc

### ISSUE THREAD

**Issue by tractormaster4596** [mbrossar/ai-imu-dr#35]
Hi,

First thanks for your great work and open source.
I have a question about the IMU state initialization. 
In your code,
      b_acc=np.zeros((N,3))
Then, you use acc = Rot_prev.dot(u[3:6] - b_acc_prev) + self.g to calculate the current acc.
In fact, u[3:6]  contains the acceleration of gravity,but the b_acc_prev does not. I cant understand why. 
In my opinion, b_acc_prev should be init as np(0,0,-9.80665).

**Comment by mbrossar** [comment]
b_acc_prev can used (i.e. set to non zero value) if you know the value of initial accelerometer bias
