### ISSUE TITLE
About the RIKEF

### ISSUE THREAD

**Issue by Iqun1314** [mbrossar/ai-imu-dr#38]
In APPENDIX A , 'As (15) are measurements expressed in the robot’s frame, they lend themselves to the Right IEKF methodology'. But I don't know why it use RIKEF? In other words, when to use LIEKF and when to use RIEKF. Thank you!

**Comment by Iqun1314** [comment]
In APPENDIX A , 'As (15) are measurements expressed in the robot’s frame, they lend themselves to the Right IEKF methodology'. But I don't know why it use RIKEF? In other words, when to use LIEKF and when to use RIEKF. Thank you!

**Comment by mbrossar** [comment]
You can see both Invariant Kalman Filtering (https://www.annualreviews.org/doi/abs/10.1146/annurev-control-060117-105010), and The Invariant Extended Kalman Filter as a Stable Observer (https://ieeexplore.ieee.org/document/7523335).

RIEKF is adapted for measurements expressed in the robot’s frame, e.g. from camera or zero lateral velocity in **body** frame.
LIEKF is well adapted for measurements expressed in the **global** frame, e.g. GPS.

**Comment by Iqun1314** [comment]
Thank you so much！

**Comment by Iqun1314** [comment]
Thank you so much！




------------------ Original ------------------

**Comment by scott81321** [comment]
I would like to understand this more.  Brossard's paper only mentions RIEKF.  I gather that RIEKF is what is implemented in his code ai-imu-dr.  Is there any way of mixing LIEKF and RIEKF?
