### ISSUE TITLE
About IEKF and trained IEKF

### ISSUE THREAD

**Issue by CChengtao** [mbrossar/ai-imu-dr#42]
Dear Martin,

First thanks for your great work and open source. This is an interesting approach!

I have one question in theory. In your paper, noise parameters Qn and Nn will be learned by a neural network. I have downloaded your project from GitHub, and tried to consider the Qn and Nn parameters use the default values and fixed. I have used both your trained model and my own trained model. However, there seems to be no obvious difference between the two methods.

Could you give me some advise about how to explain those phenomenons?

Thanks a lot.

C.Chengtao

**Comment by mbrossar** [comment]
Hello,

What you said is right: even with defaults and fixed Nn (Qn is always fixed), the filter works fine on the KITTI dataset and the differences with trained values is not obvious. This is yet indicated in the paper.

Two facts explain the above situation : 

1. The filter has been finely tuned to obtain optimal fixed Qn and Nn
2. The Kitti dataset is quite "easy" as all the trajectories are smooth and the car is almost never stopping. I can confirm you that in situation where the car has a brutal vertical movement (as in a bump), covariance need to be inflated. 

Best regards

Martin
