### ISSUE TITLE
Code not same with the algorithm

### ISSUE THREAD

**Issue by MilkCoffeeSugar** [mbrossar/ai-imu-dr#45]
Hi,

First thanks for your great work and open source.

I have run your code on my laptop, and the result is really cool. 
But I found somewhere your code not same with the paper. In the utils_numpy_filter.py, the way to calc the H_v_imu is different. 
![image](https://user-images.githubusercontent.com/20788393/82857610-10ff9800-9f44-11ea-8185-68a9f5344236.png)
![image](https://user-images.githubusercontent.com/20788393/82857670-41dfcd00-9f44-11ea-932d-dab3b8ed5a9a.png)
Could you please give me some explanation？

Thank you very much.

**Comment by Iqun1314** [comment]
你好，关于这篇代码，可以交流一下吗？我的邮箱是：landz1995@foxmail.com。
期待你的回复。
