### ISSUE TITLE
About the possibility of training on EuRoC Dataset

### ISSUE THREAD

**Issue by Beniko95J** [mbrossar/ai-imu-dr#46]
Hi, I am quite interested in your work and your results look awesome on Kitti Dataset. I think the **Pseudo-measurement** derived from car motion plays an important role in the success.  And I am wondering whether it is possible to extend your work to MAV Dataset like EuRoC dataset. Since MAV motion is more complex and there is no **Pseudo-measurement** here, I am trying to look for an alternative observation model. Currently, I am trying to fuse the translation direction ( scale is unknown) and rotation observation observed by visual information into your work, but find some trouble due to difference in frame rate of observation (from camera, 20 Hz) and IMU rate (200 Hz). 

Would you please give me some advice about this? I will really appreciate it.

Cheers

**Comment by mbrossar** [comment]
Pseudo-measurement for MAV is difficult to obtain and so it is difficult to perform pose estimation with only IMU. One can assume no acceleration in the accelerometer measurement, with is the base of the complementary filter, that provides correct attitude estimation and can not be used for position.

As you have an IMU and monocular camera, you should estimate scale, which is a challenging problem. For the different time rate, you can apply Kalman update onlu when you receive an image measurement.
