### ISSUE TITLE
Oxts files can't be read

### ISSUE THREAD

**Issue by 1248280302** [mbrossar/ai-imu-dr#56]
Hello,Martin,I'm interested in your great job.But I can't read the oxts files.
path_data_base = "/home/frost/ai-imu-dr-master/kitti"
read_data = 1
I put the oxts folder in "ai-imu-dr-master/kitti".

The result of running the code is
"
Start read_data

 Sequence name : data
Dataset is too short (0.00 s)

 Total dataset duration : 0.00 s
"
I don't know what went wrong, can you explain it?

**Comment by ajay1606** [comment]
@1248280302 Hello, thanks for your comment here. Actually, I also trying to read data from oxts file and I have set the folder path and data reading successful but there is an error when generating results. Would you please help me with how you solved this?
