### ISSUE TITLE
about use beta to  fix Q 

### ISSUE THREAD

**Issue by kahowang** [mbrossar/ai-imu-dr#60]
Hi, thank you for your really greatful work. I am learing about AI-IMU,when i   see the  
  alpha = self.factor_process_covariance(torch.ones(1).double())
            beta = 10**(self.tanh(alpha))

i dont understand why to use  beta  to  fix  the Q?
,could you please show us more detailed steps.
thanks very much.

**Comment by hqtang-git** [comment]
We can't clearly know the true value of Q, so zoom the  approximation of Q by learning approrach, just for my own understanding.
