### ISSUE TITLE
The data file is not found

### ISSUE THREAD

**Issue by devick** [mbrossar/ai-imu-dr#63]
The files can't download

https://cloud.mines-paristech.fr/index.php/s/G9frEswwgKHhnr7/download
https://cloud.mines-paristech.fr/index.php/s/XXkh5VanzDW08hD/download
https://cloud.mines-paristech.fr/index.php/s/8YDqD0Y1e6BWzCG

**Comment by mbrossar** [comment]
My cloud account of my previous university has been removed. I need to see how I can recover this files.

**Comment by JinghangLi** [comment]
Thank you for sharing the code.
Looking forward to your early restoration of the file link and thank you for your work.

**Comment by mbrossar** [comment]
Maybe if somebody yet has the files and can send them to me, I can add another link and solve that issue.

**Comment by improve100** [comment]
wait for you update new download link.

**Comment by MrNothing** [comment]
Would like to have access to the dataset too if possible. Thank you!

**Comment by wohaoshuai** [comment]
Thanks you!

**Comment by KleistvonLiu** [comment]
Also eager for access to the dataset if possible. Thank you!

**Comment by lonlonago** [comment]
need the file too, ths~   send me 394467238@qq.com

**Comment by scott81321** [comment]
I would also like these 'download' files.  Without access to these datasets, how can we test ai-imu-dr?

**Comment by zhangjinglin888** [comment]
I also need the file too, ths~ send me 2262640702@qq.com

**Comment by zhangjinglin888** [comment]
大哥 跪求数据集和训练模型

**Comment by mbrossar** [comment]
Pickle files are now available at new url, please see the [readme](https://github.com/mbrossar/ai-imu-dr)

**Comment by scott81321** [comment]
Cher Martin

Merci bien de la restoration de vos données!

Salutations

Tony Scott


On Sunday, December 19, 2021, 05:02:02 PM GMT+7, Martin Brossard ***@***.***> wrote: 


Pickle files are now available at new url, please see the readme

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
