### ISSUE TITLE
Issue on the ai-imu-dr with the compiling and running python main file.

### ISSUE THREAD

**Issue by EdernOllivier** [mbrossar/ai-imu-dr#67]
Dear Martin, I have been installing the software to run the EKF, I had several errors, which are :
ollivier@ollivier-ASUS-D300TA-S300MA:~/ai-imu-dr/src$ python3 main_kitti.py
/home/ollivier/ai-imu-dr/src/train_torch_filter.py:127: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(rpe[0]) is not 0:
/home/ollivier/ai-imu-dr/src/train_torch_filter.py:137: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(rpe[0]) is not 0:
/home/ollivier/ai-imu-dr/src/train_torch_filter.py:159: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if loss is -1 or torch.isnan(loss):
/home/ollivier/ai-imu-dr/src/train_torch_filter.py:265: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(idxs_0_bis) is 0:
Traceback (most recent call last):
  File "main_kitti.py", line 482, in <module>
    dataset = KITTIDataset(args)
  File "main_kitti.py", line 119, in __init__
    super(KITTIDataset, self).__init__(args)
  File "/home/ollivier/ai-imu-dr/src/dataset.py", line 53, in __init__
    self.get_datasets()
  File "/home/ollivier/ai-imu-dr/src/dataset.py", line 64, in get_datasets
    for dataset in os.listdir(self.path_data_save):
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '../data'

and also :
ollivier@ollivier-ASUS-D300TA-S300MA:~$ wget "https://cloud.mines-paristech.fr/index.php/s/XXkh5VanzDW08hD/download"
--2021-10-10 12:38:42--  https://cloud.mines-paristech.fr/index.php/s/XXkh5VanzDW08hD/download
Résolution de cloud.mines-paristech.fr (cloud.mines-paristech.fr)... 77.158.180.133
Connexion vers cloud.mines-paristech.fr (cloud.mines-paristech.fr)|77.158.180.133|:443... connecté.
requête HTTP transmise, en attente de la réponse... 503 Service Unavailable
2021-10-10 12:38:42 ERREUR 503: Service Unavailable.

Tell me if it can be fixed.

Best regards, Edern Ollivier.

**Comment by scott81321** [comment]
Hello Edern Ollivier

I also get the wget error.  It seems that Martin Brossard no longer has/had his University account which had these datasets.  There is a complaint or two on that issue in another thread for which I also responded.

**Comment by EdernOllivier** [comment]
Dear  Scott, thank to you, I dont have made any progress with the Martin's program and I am using Linux Ubuntu to program in C. Best regards, Edern Ollivier.

**Comment by scott81321** [comment]
If you are not using Martin's program, what are you using?

**Comment by EdernOllivier** [comment]
Dear Scott, I am using a simple Kalman filtering technique supported by an Aduino Due board and libraries in C++, please check the source in my github at "https://github.com/EdernOllivier/GeographicalRecalibrationDue", its payload is minimal to get the best values said to be optimal in the space of the geography and timed buffered of the IMU/GPS recalibration. Best regards, Edern Ollivier.

**Comment by scott81321** [comment]
Do you know of an alternative and/or competitor to Brossard's program.  I still cannot get  a hold of him.  I need a (free) dead reckoning program that tales IMU accel + gyrp and GPS (lat,long and alt) by which to predict the path of a moving vehicle when it e.g. goes into a tunnel and GPS is no longer active?

**Comment by EdernOllivier** [comment]
I dont know an alternative for this program, maybe with a research center in France ?

**Comment by EdernOllivier** [comment]
Actually the team of researchers of them has been doing a lot of maths for the fusion algorithm, and I am deeply impressed by the tool of the Lie Algebra. Maybe that something is going to be discovered soon.
