### ISSUE TITLE
Cannot access url for data and train parameters

### ISSUE THREAD

**Issue by jay-95** [mbrossar/ai-imu-dr#68]
Hi.
I cannot access these links for data.
[url1](https://cloud.mines-paristech.fr/index.php/s/G9frEswwgKHhnr7/download)
[url2](https://cloud.mines-paristech.fr/index.php/s/XXkh5VanzDW08hD/download)

As I am watching the issues, I notice it because of author's account issue.
However, there's no new links for solution for link.

Please, ask someone who already have dataset attach new link or contact email
dnjswo0205@dgist.ac.kr

If I get dataset, I'm going to share the link for solving the issue #63 

Thanks

**Comment by mbrossar** [comment]
Pickle files are now available at new url, please see the [readme](https://github.com/mbrossar/ai-imu-dr)
