### ISSUE TITLE
Dataset.py Path

### ISSUE THREAD

**Issue by prayritkhanna** [mbrossar/ai-imu-dr#7]
Hello, 

I am researching an imu project and have been reading your paper as reference for my research. I was hoping you could clarify where (path_data_save) is saving in dataset.py line 64. If you could get back to me as soon as possible that would be great!

**Comment by mbrossar** [comment]
path_data_save is a path that indicates where preprocessing data have been saved. Preprocessing data are just a part of the KITTI data saved in pickle format for fast loading.
In the main_kitti.py file , we have path_data_save = "../data".
