### ISSUE TITLE
about sup.pdf

### ISSUE THREAD

**Issue by yuqJin** [mbrossar/ai-imu-dr#73]
This is a very good example about solving H, but I would like to ask about this step
![image](https://user-images.githubusercontent.com/34875284/159635780-f63ffde2-4ba8-4c5a-83db-3e2aeb70c3d3.png)
The transpose is gone. And the content in the second bracket does not correspond to formula (5). Can someone explain it to me? thank you very much!

**Comment by Rajat-Arora** [comment]
Hey @yuqJin were you able to figure it out?

**Comment by paaraujo** [comment]
@Rajat-Arora, I hope this can help:

![equation](https://user-images.githubusercontent.com/7448345/200601184-e48d99f4-d775-4455-81b7-6531b3769767.PNG)

**Comment by Rajat-Arora** [comment]
@paaraujo Thanks a lot for your help. 
Could you please help me derive the complete H matrix of variables corresponding to biases and car to imu rotation and translation?
Specifically, the last 4 terms in the H matrix.
![image](https://user-images.githubusercontent.com/97186785/200647444-d6341e3e-ca72-49ea-b9d3-a44101d9436c.png)

I would be really grateful for your help.

**Comment by Rajat-Arora** [comment]
Hi @paaraujo, could you please describe more about how did you get the negative sign in the bracket in the following equation?
![image](https://user-images.githubusercontent.com/97186785/202355658-31bf0ac4-e035-4e06-9fe1-cbdc7f2b921e.png)

According to me and following sup.pdf after linearization, it should become,
![image](https://user-images.githubusercontent.com/97186785/202356043-7ad6758e-1857-4222-8b98-b1d0db2e0490.png)
and not
![image](https://user-images.githubusercontent.com/97186785/202356115-316cf0ba-9c59-4c08-9247-8c96ffb788fb.png)

Could you please describe how did you get it?

Also, after getting R, why didn't we take a transpose while substituting it into equation number 6?

**Comment by linsongxue** [comment]
> Hi @paaraujo, could you please describe more about how did you get the negative sign in the bracket in the following equation? ![image](https://user-images.githubusercontent.com/97186785/202355658-31bf0ac4-e035-4e06-9fe1-cbdc7f2b921e.png)
> 
> According to me and following sup.pdf after linearization, it should become, ![image](https://user-images.githubusercontent.com/97186785/202356043-7ad6758e-1857-4222-8b98-b1d0db2e0490.png) and not ![image](https://user-images.githubusercontent.com/97186785/202356115-316cf0ba-9c59-4c08-9247-8c96ffb788fb.png)
> 
> Could you please describe how did you get it?
> 
> Also, after getting R, why didn't we take a transpose while substituting it into equation number 6?

Hi @Rajat-Arora, have you solved this question? Would you mind sharing the solution if you have done.
